name: GetEgged
version: '0.8.3'
main: io.jimbonesjim.getEgged.GetEgged
api-version: '1.21'
authors: [ PopTart_Flavored ]
description: Capture mobs into spawn eggs while preserving mob data.

commands:
  getegged:
    description: Gives you capture item.
    aliases: [ge]
    default: op
    usage: /<command> <get/reload/give>

permissions:
  getegged.get:
    default: true
  getegged.give:
    default: op
  getegged.reload:
    default: op
  getegged.tamed:
    default: op
  getegged.animal.*:
    default: op
  getegged.monster.*:
    default: op
  getegged.golem.*:
    default: op